import { AntdRegistry } from '@ant-design/nextjs-registry';
import { themeConfig } from '@skeleton/shared';
import { ConfigProvider } from 'antd';
import './global.css';
export const metadata = {
  title: 'Welcome to owner',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              ...themeConfig
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
